// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Varde.Data;

#nullable disable

namespace Varde.Data.Migrations
{
    [DbContext(typeof(VardeDbContext))]
    partial class VardeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Varde.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Slug = "okonomi"
                        },
                        new
                        {
                            Id = 2,
                            Slug = "bolig"
                        },
                        new
                        {
                            Id = 3,
                            Slug = "psykisk-helse"
                        },
                        new
                        {
                            Id = 4,
                            Slug = "rus"
                        },
                        new
                        {
                            Id = 5,
                            Slug = "vold-og-overgrep"
                        },
                        new
                        {
                            Id = 6,
                            Slug = "familie-og-barn"
                        },
                        new
                        {
                            Id = 7,
                            Slug = "arbeid"
                        },
                        new
                        {
                            Id = 8,
                            Slug = "juridisk-hjelp"
                        },
                        new
                        {
                            Id = 9,
                            Slug = "nodtjenester"
                        });
                });

            modelBuilder.Entity("Varde.Core.Models.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("CategoryTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            LanguageCode = "nb",
                            Name = "Økonomi og gjeld"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            LanguageCode = "en",
                            Name = "Money and debt"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            LanguageCode = "nb",
                            Name = "Bolig"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            LanguageCode = "en",
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            LanguageCode = "nb",
                            Name = "Psykisk helse"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            LanguageCode = "en",
                            Name = "Mental health"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            LanguageCode = "nb",
                            Name = "Rus og avhengighet"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            LanguageCode = "en",
                            Name = "Substance use and addiction"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            LanguageCode = "nb",
                            Name = "Vold og overgrep"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            LanguageCode = "en",
                            Name = "Violence and abuse"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            LanguageCode = "nb",
                            Name = "Familie og barn"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            LanguageCode = "en",
                            Name = "Family and children"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            LanguageCode = "nb",
                            Name = "Arbeid"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            LanguageCode = "en",
                            Name = "Work"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            LanguageCode = "nb",
                            Name = "Juridisk hjelp"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            LanguageCode = "en",
                            Name = "Legal help"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            LanguageCode = "nb",
                            Name = "Nødtjenester"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            LanguageCode = "en",
                            Name = "Emergency services"
                        });
                });

            modelBuilder.Entity("Varde.Core.Models.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Municipalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            County = "Innlandet",
                            Name = "Hamar"
                        },
                        new
                        {
                            Id = 2,
                            County = "Innlandet",
                            Name = "Lillehammer"
                        },
                        new
                        {
                            Id = 3,
                            County = "Innlandet",
                            Name = "Gjøvik"
                        },
                        new
                        {
                            Id = 4,
                            County = "Innlandet",
                            Name = "Ringsaker"
                        },
                        new
                        {
                            Id = 5,
                            County = "Innlandet",
                            Name = "Stange"
                        },
                        new
                        {
                            Id = 6,
                            County = "Innlandet",
                            Name = "Løten"
                        },
                        new
                        {
                            Id = 7,
                            County = "Innlandet",
                            Name = "Elverum"
                        },
                        new
                        {
                            Id = 8,
                            County = "Oslo",
                            Name = "Oslo"
                        });
                });

            modelBuilder.Entity("Varde.Core.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ChatUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsNational")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LastVerified")
                        .HasColumnType("date");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("IsNational", "Name", "Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Hjelpetelefonen (Mental Helse)",
                            Phone = "116 123",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://mentalhelse.no"
                        },
                        new
                        {
                            Id = 2,
                            ChatUrl = "https://www.soschat.no",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Kirkens SOS",
                            Phone = "22 40 00 40",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.kirkens-sos.no"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Legevakt",
                            Phone = "116 117",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.helsenorge.no/legevakt/"
                        },
                        new
                        {
                            Id = 4,
                            ChatUrl = "https://www.116111.no",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Alarmtelefonen for barn og unge",
                            Phone = "116 111",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.116111.no"
                        },
                        new
                        {
                            Id = 5,
                            ChatUrl = "https://www.volinjen.no",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "VO-linjen",
                            Phone = "116 006",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.volinjen.no"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Navs økonomi- og gjeldsveiledningstelefon",
                            Phone = "55 55 33 39",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.nav.no"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Jussbuss",
                            Phone = "22 84 29 00",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://foreninger.uio.no/jussbuss/"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Rustelefonen",
                            Phone = "915 08 588",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://rustelefonen.no"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = true,
                            LastVerified = new DateOnly(2026, 8, 13),
                            Name = "Arbeidslivstelefonen (Mental Helse)",
                            Phone = "116 123",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://mentalhelse.no"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Vangsvegen 121, 2318 Hamar",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 1,
                            Name = "Familievernkontoret Innlandet Øst, avdeling Hamar",
                            Phone = "466 17 130",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.bufdir.no/familie/familievernkontorer/oversikt/innlandet-ost/"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Torggata 63, 2317 Hamar",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 1,
                            Name = "Nav Hamar",
                            Phone = "55 55 33 33",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.nav.no"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kronborgveien 23, 2318 Hamar",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 1,
                            Name = "Hamar interkommunale krisesenter",
                            Phone = "62 56 18 30",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.hamar.kommune.no/familiehjelp-oversikt-over-tilbud/krisesenter/"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Vangsvegen 121, 2318 Hamar",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 1,
                            Name = "Tjeneste psykisk helse og rus, Hamar kommune",
                            Phone = "916 03 327",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.hamar.kommune.no/helseogomsorg/psykisk-helse-og-rus/"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 1,
                            Name = "Ringsaker interkommunale barnevernvakt",
                            Phone = "404 04 015",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.hamar.kommune.no/familiehjelp-oversikt-over-tilbud/hjelpetelefoner-for-familier-og-barn-unge/"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 2,
                            Name = "Rask psykisk helsehjelp, Lillehammer kommune",
                            Phone = "917 13 338",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://lillehammer.kommune.no/helse-og-velferd/psykisk-helse-og-rus/"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Skoletorget 6 D, 2609 Lillehammer",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 2,
                            Name = "Gudbrandsdal Krisesenter IKS",
                            Phone = "414 81 220",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://gudbrandsdal-krisesenter.no"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 2,
                            Name = "Housing First, Lillehammer kommune",
                            Phone = "451 64 131",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://lillehammer.kommune.no/helse-og-velferd/psykisk-helse-og-rus/"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 2,
                            Name = "Oppfølgingsteamet, Lillehammer kommune",
                            Phone = "902 43 733",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://lillehammer.kommune.no/helse-og-velferd/psykisk-helse-og-rus/"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 2,
                            Name = "Mottak for seksuelle overgrep, Lillehammer",
                            Phone = "61 27 22 16",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://lillehammer.kommune.no/om-kommunen/kontakt-oss/nod-og-vakttelefoner/"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Parkgata 10 A, 2815 Gjøvik",
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 3,
                            Name = "Nav Gjøvik",
                            Phone = "55 55 33 33",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.nav.no"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 3,
                            Name = "Gjøvik Krisesenter IKS",
                            Phone = "61 17 55 60",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.krisesenteret-gjovik.no"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsNational = false,
                            LastVerified = new DateOnly(2026, 8, 13),
                            MunicipalityId = 3,
                            Name = "Jobbhus Gjøvik",
                            UpdatedAt = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.gjovik.kommune.no/jobbhus/jeg-onsker-jobb/"
                        });
                });

            modelBuilder.Entity("Varde.Core.Models.ResourceCategory", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("ResourceId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ResourceCategories");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 3,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 4,
                            CategoryId = 6
                        },
                        new
                        {
                            ResourceId = 4,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 4,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 5,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            ResourceId = 7,
                            CategoryId = 8
                        },
                        new
                        {
                            ResourceId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            ResourceId = 9,
                            CategoryId = 7
                        },
                        new
                        {
                            ResourceId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 10,
                            CategoryId = 6
                        },
                        new
                        {
                            ResourceId = 11,
                            CategoryId = 1
                        },
                        new
                        {
                            ResourceId = 11,
                            CategoryId = 7
                        },
                        new
                        {
                            ResourceId = 12,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 12,
                            CategoryId = 2
                        },
                        new
                        {
                            ResourceId = 12,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 13,
                            CategoryId = 4
                        },
                        new
                        {
                            ResourceId = 14,
                            CategoryId = 6
                        },
                        new
                        {
                            ResourceId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 14,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 15,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 15,
                            CategoryId = 4
                        },
                        new
                        {
                            ResourceId = 16,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 16,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 17,
                            CategoryId = 2
                        },
                        new
                        {
                            ResourceId = 17,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 18,
                            CategoryId = 4
                        },
                        new
                        {
                            ResourceId = 18,
                            CategoryId = 3
                        },
                        new
                        {
                            ResourceId = 19,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 19,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 20,
                            CategoryId = 1
                        },
                        new
                        {
                            ResourceId = 20,
                            CategoryId = 7
                        },
                        new
                        {
                            ResourceId = 20,
                            CategoryId = 2
                        },
                        new
                        {
                            ResourceId = 21,
                            CategoryId = 5
                        },
                        new
                        {
                            ResourceId = 21,
                            CategoryId = 9
                        },
                        new
                        {
                            ResourceId = 22,
                            CategoryId = 7
                        });
                });

            modelBuilder.Entity("Varde.Core.Models.ResourceMunicipality", b =>
                {
                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("integer");

                    b.HasKey("ResourceId", "MunicipalityId");

                    b.HasIndex("MunicipalityId");

                    b.ToTable("ResourceMunicipalities");
                });

            modelBuilder.Entity("Varde.Core.Models.ResourceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ResourceTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gratis og døgnåpen telefontjeneste for alle som trenger noen å snakke med om det som er vanskelig. Du kan være anonym, og de som svarer har taushetsplikt.",
                            LanguageCode = "nb",
                            OpeningHours = "Døgnåpent",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A free 24-hour phone line for anyone who needs someone to talk to about what is difficult. You can stay anonymous, and everyone who answers is bound by confidentiality.",
                            LanguageCode = "en",
                            OpeningHours = "Open 24 hours",
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Døgnåpen krisetelefon for deg som har det vanskelig eller tenker på selvmord. Tjenesten er anonym, og du trenger ikke ha en bestemt grunn for å ringe.",
                            LanguageCode = "nb",
                            OpeningHours = "Døgnåpent",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "A 24-hour crisis line for anyone in distress or having thoughts of suicide. The service is anonymous, and you do not need a particular reason to call.",
                            LanguageCode = "en",
                            OpeningHours = "Open 24 hours",
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nasjonalt nummer som setter deg over til legevaktsentralen der du befinner deg, når fastlegen er stengt og du trenger hjelp raskt. Ved akutt livsfare skal du ringe 113.",
                            LanguageCode = "nb",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "A national number that connects you to the out-of-hours medical service where you are, when your regular doctor is closed and you need help quickly. In a life-threatening emergency, call 113 instead.",
                            LanguageCode = "en",
                            ResourceId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Gratis døgnåpen telefon for barn og unge som opplever vold, overgrep eller omsorgssvikt. Voksne som er bekymret for et barn kan også ringe.",
                            LanguageCode = "nb",
                            OpeningHours = "Døgnåpent",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "A free 24-hour phone line for children and young people experiencing violence, abuse or neglect. Adults who are worried about a child can call too.",
                            LanguageCode = "en",
                            OpeningHours = "Open 24 hours",
                            ResourceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Hjelpelinje for deg som opplever vold eller overgrep i nære relasjoner. Også for pårørende og hjelpere, og du kan være helt anonym.",
                            LanguageCode = "nb",
                            OpeningHours = "Døgnåpent",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "A helpline for anyone experiencing violence or abuse in a close relationship. It is also for relatives and professionals, and you can remain completely anonymous.",
                            LanguageCode = "en",
                            OpeningHours = "Open 24 hours",
                            ResourceId = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "Gratis veiledning for deg som har økonomiske problemer eller gjeld du ikke klarer å betjene. Du kan få hjelp til å få oversikt over økonomien og sette opp et realistisk budsjett.",
                            LanguageCode = "nb",
                            OpeningHours = "Hverdager 09:00–15:00",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 12,
                            Description = "Free guidance for anyone with money problems or debt they cannot manage. You can get help mapping out your finances and building a budget you can actually live with.",
                            LanguageCode = "en",
                            OpeningHours = "Weekdays 09:00–15:00",
                            ResourceId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "Gratis rettshjelp fra jusstudenter i saker om blant annet husleie, gjeld, trygd, arbeid, utlendingsrett og fengsel. Du trenger ikke advokat for å ta kontakt.",
                            LanguageCode = "nb",
                            OpeningHours = "Mandag 17:00–20:00 og tirsdag 10:00–15:00",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 14,
                            Description = "Free legal aid from law students in areas such as rent, debt, benefits, employment, immigration and prison law. You do not need a lawyer to get in touch.",
                            LanguageCode = "en",
                            OpeningHours = "Monday 17:00–20:00 and Tuesday 10:00–15:00",
                            ResourceId = 7
                        },
                        new
                        {
                            Id = 15,
                            Description = "Anonym telefontjeneste for spørsmål om rus, både for deg som bruker rusmidler selv og for pårørende. Du får informasjon og veiledning uten å bli møtt med pekefinger. Kortnummeret 08588 brukes også for tjenesten.",
                            LanguageCode = "nb",
                            OpeningHours = "Hverdager 11:00–14:30 og 15:00–18:00",
                            ResourceId = 8
                        },
                        new
                        {
                            Id = 16,
                            Description = "An anonymous phone service for questions about drugs and alcohol, both for people who use substances and for their families. You get information and guidance without being judged. The short code 08588 is also used for the service.",
                            LanguageCode = "en",
                            OpeningHours = "Weekdays 11:00–14:30 and 15:00–18:00",
                            ResourceId = 8
                        },
                        new
                        {
                            Id = 17,
                            Description = "Rådgivning om vanskelige forhold på jobben, som konflikt, mobbing, sykefravær eller oppsigelse. Åpen for arbeidstakere, ledere, tillitsvalgte og arbeidssøkere. Velg tast 3 i menyen.",
                            LanguageCode = "nb",
                            ResourceId = 9
                        },
                        new
                        {
                            Id = 18,
                            Description = "Advice about difficult situations at work, such as conflict, bullying, sick leave or dismissal. Open to employees, managers, union representatives and jobseekers. Choose option 3 in the menu.",
                            LanguageCode = "en",
                            ResourceId = 9
                        },
                        new
                        {
                            Id = 19,
                            Description = "Gratis tilbud om samtale, parterapi og mekling for familier, par og enkeltpersoner. Du trenger ingen henvisning for å bestille time.",
                            LanguageCode = "nb",
                            OpeningHours = "08:30–15:00, redusert om sommeren",
                            ResourceId = 10
                        },
                        new
                        {
                            Id = 20,
                            Description = "A free service offering counselling, couples therapy and mediation for families, couples and individuals. No referral is needed to book an appointment.",
                            LanguageCode = "en",
                            OpeningHours = "08:30–15:00, reduced in summer",
                            ResourceId = 10
                        },
                        new
                        {
                            Id = 21,
                            Description = "Nav-kontoret for innbyggere i Hamar, med hjelp til økonomisk sosialhjelp, arbeid og andre sosiale tjenester. Du kan møte opp uten avtale i drop-in-tiden, eller avtale time på forhånd.",
                            LanguageCode = "nb",
                            OpeningHours = "Drop-in mandag og onsdag 12:00–14:00, fredag 10:00–12:00",
                            ResourceId = 11
                        },
                        new
                        {
                            Id = 22,
                            Description = "The Nav office for people living in Hamar, offering help with financial assistance, work and other social services. You can come without an appointment during drop-in hours, or book a time in advance.",
                            LanguageCode = "en",
                            OpeningHours = "Drop-in Monday and Wednesday 12:00–14:00, Friday 10:00–12:00",
                            ResourceId = 11
                        },
                        new
                        {
                            Id = 23,
                            Description = "Gratis døgnåpent tilbud til kvinner, menn, barn og eldre som er utsatt for vold i nære relasjoner. Senteret tilbyr både beskyttet botilbud og samtaler for dem som ikke trenger å bo der.",
                            LanguageCode = "nb",
                            OpeningHours = "Døgnåpent",
                            ResourceId = 12
                        },
                        new
                        {
                            Id = 24,
                            Description = "A free 24-hour service for women, men, children and older people affected by violence in close relationships. The centre offers both protected accommodation and counselling for those who do not need to stay.",
                            LanguageCode = "en",
                            OpeningHours = "Open 24 hours",
                            ResourceId = 12
                        },
                        new
                        {
                            Id = 25,
                            Description = "Kommunens tilbud til voksne med psykiske vansker eller rusproblemer, med samtaler, oppfølging og praktisk hjelp i hverdagen. Du kan ta kontakt selv, uten henvisning fra lege.",
                            LanguageCode = "nb",
                            OpeningHours = "Kun dagtid",
                            ResourceId = 13
                        },
                        new
                        {
                            Id = 26,
                            Description = "The municipality's service for adults with mental health or substance use difficulties, offering counselling, follow-up and practical everyday support. You can make contact yourself, without a doctor's referral.",
                            LanguageCode = "en",
                            OpeningHours = "Daytime only",
                            ResourceId = 13
                        },
                        new
                        {
                            Id = 27,
                            Description = "Barnevernets akuttberedskap på kveld, natt, helg og helligdager for barn og unge i akutte situasjoner. Både barn selv og voksne som er bekymret kan ringe.",
                            LanguageCode = "nb",
                            OpeningHours = "Kveld og natt 15:30–08:00, samt helger og helligdager",
                            ResourceId = 14
                        },
                        new
                        {
                            Id = 28,
                            Description = "The child welfare emergency service, staffed evenings, nights, weekends and public holidays for children and young people in urgent situations. Both children themselves and worried adults can call.",
                            LanguageCode = "en",
                            OpeningHours = "Evenings and nights 15:30–08:00 plus weekends and holidays",
                            ResourceId = 14
                        },
                        new
                        {
                            Id = 29,
                            Description = "Korttidsbehandling for deg fra 16 år med lettere angst, depresjon, søvnvansker eller begynnende rusproblemer. Tilbudet er gratis, og du trenger ikke henvisning fra fastlegen.",
                            LanguageCode = "nb",
                            OpeningHours = "Mandag og onsdag 11:30–13:00",
                            ResourceId = 15
                        },
                        new
                        {
                            Id = 30,
                            Description = "Short-term treatment for people aged 16 and over with mild anxiety, depression, sleep problems or early substance use difficulties. The service is free and needs no referral from your doctor.",
                            LanguageCode = "en",
                            OpeningHours = "Monday and Wednesday 11:30–13:00",
                            ResourceId = 15
                        },
                        new
                        {
                            Id = 31,
                            Description = "Krisesenter for kvinner, menn og barn som er utsatt for vold eller trusler om vold i nære relasjoner. Tilbudet er gratis, og du trenger ingen henvisning.",
                            LanguageCode = "nb",
                            ResourceId = 16
                        },
                        new
                        {
                            Id = 32,
                            Description = "A crisis centre for women, men and children affected by violence or threats of violence in close relationships. The service is free and needs no referral.",
                            LanguageCode = "en",
                            ResourceId = 16
                        },
                        new
                        {
                            Id = 33,
                            Description = "Tilbud til bostedsløse med rus- eller psykiske helseutfordringer, der du først får en varig bolig og deretter oppfølging der du bor. Målet er en stabil bosituasjon uten krav om rusfrihet på forhånd.",
                            LanguageCode = "nb",
                            OpeningHours = "Hverdager 09:00–15:00",
                            ResourceId = 17
                        },
                        new
                        {
                            Id = 34,
                            Description = "A service for homeless people with substance use or mental health difficulties, where you first get permanent housing and then receive support where you live. The aim is a stable home without requiring sobriety first.",
                            LanguageCode = "en",
                            OpeningHours = "Weekdays 09:00–15:00",
                            ResourceId = 17
                        },
                        new
                        {
                            Id = 35,
                            Description = "Team som gir tett oppfølging til voksne med rusproblemer eller psykiske helseutfordringer i hverdagen. Teamet har lang åpningstid, også i helgene.",
                            LanguageCode = "nb",
                            OpeningHours = "Hver dag 09:00–21:00",
                            ResourceId = 18
                        },
                        new
                        {
                            Id = 36,
                            Description = "A team providing close everyday follow-up for adults with substance use or mental health difficulties. The team has long opening hours, including weekends.",
                            LanguageCode = "en",
                            OpeningHours = "Every day 09:00–21:00",
                            ResourceId = 18
                        },
                        new
                        {
                            Id = 37,
                            Description = "Medisinsk hjelp, undersøkelse og sporsikring for deg som har vært utsatt for voldtekt eller seksuelt overgrep. Du kan ta kontakt uten å ha anmeldt forholdet til politiet.",
                            LanguageCode = "nb",
                            ResourceId = 19
                        },
                        new
                        {
                            Id = 38,
                            Description = "Medical care, examination and forensic evidence collection for people who have experienced rape or sexual assault. You can get in touch without having reported it to the police.",
                            LanguageCode = "en",
                            ResourceId = 19
                        },
                        new
                        {
                            Id = 39,
                            Description = "Nav-kontoret for innbyggere i Gjøvik, med oppfølging innen økonomi, arbeid, bolig og sosiale tjenester. Du kan komme innom i drop-in-tiden eller avtale time.",
                            LanguageCode = "nb",
                            OpeningHours = "Hverdager 09:00–15:00",
                            ResourceId = 20
                        },
                        new
                        {
                            Id = 40,
                            Description = "The Nav office for people living in Gjøvik, offering support with money, work, housing and social services. You can drop in during open hours or book an appointment.",
                            LanguageCode = "en",
                            OpeningHours = "Weekdays 09:00–15:00",
                            ResourceId = 20
                        },
                        new
                        {
                            Id = 41,
                            Description = "Gratis døgnåpent tilbud til kvinner, menn og barn som er utsatt for vold i nære relasjoner, voldtekt eller tvangsekteskap. Adressen oppgis først når du tar kontakt, av hensyn til sikkerheten.",
                            LanguageCode = "nb",
                            OpeningHours = "Døgnåpent",
                            ResourceId = 21
                        },
                        new
                        {
                            Id = 42,
                            Description = "A free 24-hour service for women, men and children affected by violence in close relationships, rape or forced marriage. The address is only given when you make contact, for safety reasons.",
                            LanguageCode = "en",
                            OpeningHours = "Open 24 hours",
                            ResourceId = 21
                        },
                        new
                        {
                            Id = 43,
                            Description = "Hjelp til å komme i arbeid for deg mellom 16 og 30 år i Gjøvik, med veiledning, jobbsøking, CV og arbeidspraksis. Drop-in-tilbudet er åpent for alle arbeidssøkere uansett alder og bosted.",
                            LanguageCode = "nb",
                            ResourceId = 22
                        },
                        new
                        {
                            Id = 44,
                            Description = "Help getting into work for people aged 16 to 30 in Gjøvik, with guidance, job applications, CV writing and work placements. The drop-in service is open to all jobseekers regardless of age or where they live.",
                            LanguageCode = "en",
                            ResourceId = 22
                        });
                });

            modelBuilder.Entity("Varde.Core.Models.CategoryTranslation", b =>
                {
                    b.HasOne("Varde.Core.Models.Category", "Category")
                        .WithMany("Translations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Varde.Core.Models.Resource", b =>
                {
                    b.HasOne("Varde.Core.Models.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Varde.Core.Models.ResourceCategory", b =>
                {
                    b.HasOne("Varde.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varde.Core.Models.Resource", "Resource")
                        .WithMany("ResourceCategories")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Varde.Core.Models.ResourceMunicipality", b =>
                {
                    b.HasOne("Varde.Core.Models.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Varde.Core.Models.Resource", "Resource")
                        .WithMany("ServedMunicipalities")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Municipality");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Varde.Core.Models.ResourceTranslation", b =>
                {
                    b.HasOne("Varde.Core.Models.Resource", "Resource")
                        .WithMany("Translations")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Varde.Core.Models.Category", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Varde.Core.Models.Resource", b =>
                {
                    b.Navigation("ResourceCategories");

                    b.Navigation("ServedMunicipalities");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
