// Generated by web/scripts/brand.mjs from web/scripts/brand-geometry.mjs. Do not edit:
// change the geometry and run `npm run brand`. tests/brand.test.ts fails on drift.
export const RING = {"cx":16,"cy":16,"r":14.6,"strokeWidth":2.4} as const
export const CLIP_R = 13.6
export const FJORD_LINES = [{"y":25.9,"strokeWidth":1.2},{"y":28.3,"strokeWidth":1}] as const
export const MOUNTAIN_POINTS = "-2.4,30.8 5.88,20.86 8.27,22.34 12.5,19.02 16,17.74 19.5,19.02 22.62,22.15 24.83,20.86 34.4,30.8"
export const STONE_POINTS = ["13.55,9.3 13.28,7.77 13.83,6.36 16.27,6.24 17.3,6.48 18.17,6.85 18.72,8.14 18.45,9.3","12.55,13.14 12.17,11.46 12.93,9.93 16.38,9.79 17.84,10.06 19.07,10.46 19.83,11.87 19.45,13.14","11.92,17.25 11.47,15.44 12.38,13.77 16.45,13.62 18.17,13.91 19.62,14.35 20.53,15.87 20.08,17.25"] as const
